### ISSUE TITLE
Possible account creation race condition

### ISSUE THREAD

**Issue by Taffer** [auroris/City-of-Heroes-Account-Portal#8]
There's a potential race condition ([TOCTOU](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) error) at line 61 in `App/Model/GameAccount.cpp` if two people are creating an account at the same time (unless the server only runs a single thread or the web app framework serializes requests automagically).

If two (or more) people are hitting that code at the same time, more than one of them could get the same User ID because `SELECT max(uid)` will be returning the same value until the database insert happens down at line 78.

The fix for this is to make the User ID column auto-increment, remove User ID from the `INSERT` in `sql1`, then split out the remaining `INSERT`s so you can get the newly created User ID to use in `$sql3` and `$sql4`.

**Comment by auroris** [comment]
As per the recommendations in my readme.md:
> Add a unique index to column uid on cohauth.dbo.user_account to reduce the possibility of account uid collisions. To do that, run this SQL statement: `CREATE UNIQUE INDEX AccountUID ON cohauth.dbo.user_account (uid);`

Unless there's something else I'm potentially missing?

**Comment by auroris** [comment]
As an addendum, I use transactions during account creation to ensure that it either all succeeds, or all fails. While the race condition still exists, it won't impact accounts. Somebody will simply get an error message. As I'm not the only one potentially poking accounts into the database, an auto-increment would affect those other products. In any event, I judge the likelihood for a uid collision to be unlikely enough that it's not worth worrying about, but dangerous enough that the unique index protection mitigates it.

**Comment by Taffer** [comment]
Ah, I should have looked at the DB constraints. If someone runs into this race condition, it'll manifest as an error on `INSERT`, and the transaction will ensure that nothing's left in a weird state. 👍
